### ISSUE TITLE
RTL8723DE

### ISSUE THREAD

**Issue by pandey246** [lwfinger/rtl8723be#13]
I'm using kali linux in a dual boot system.My wifi is not visible and i have RTL8723DE wifi card.Will you help me out.I followed everything mentioned here.Installed rtlwifi_new.After a lot of efforts wifi is visible but its strength is very very weak.ant_sel is also not working.neither tx power is increasing.Is RTL8723DE will never support wifi???

**Comment by lwfinger** [comment]
Do you really have to run everything together? As far as I know, GitHub does not charge by the character.Certainly you could put a space after the period.Can you not?Remember that I am a volunteer and you are asking for my time.Make things as good as you can for me.

With my RTL8723DE that has one antenna connector, the signal from my AP is -68 dBm when I do not specify a value for ant_sel. When I use ant_sel=1, I get -65 dBm - no change. When I use ant_sel=2, that signal strength jumps to -19 dBm. The code is doing exactly what it should. I have no idea what you are doing wrong!

**Comment by pandey246** [comment]
Now, there's no more RTL8723DE file in rtlwifi_new.Will you help me out , Please...

**Comment by lwfinger** [comment]
When you change the kernel, you ALWAYS need to rebuild every out-of-kernel driver. You can either do it manually, or you can implement dkms.

What do you mean there is no more RTL8723DE in rtlwifi_new. Are you using the wrong branch? The "master" branch does not contain RTL8723DE, but "extended" does.

**Comment by pandey246** [comment]
Will you provide me that link.. I'm not getting it.

**Comment by lwfinger** [comment]
git clone http://gitcub.com/lwfinger/rtlwifi_new.git -b extended

**Comment by pandey246** [comment]
I use this and now wifi is  visible but strength of signal is too poor that it is not able to connect.

**Comment by pandey246** [comment]
Wifi networks are not stable.They come and go very frequently.

**Comment by lwfinger** [comment]
Do you need to use an ant_sel value? Is your computer one of those units that has only one antenna and a misconfigured ROM?

**Comment by pandey246** [comment]
I don't about this sir

**Comment by pandey246** [comment]
I have rtl8723de wifi card and HP 15BS576TX model notebook

**Comment by pandey246** [comment]
I used These commands:
git clone -b extended --single-branch https://github.com/lwfinger/rtlwifi_new.git
make
make install

After reboot wifi is enabled but strength is too weak and not able to connect with qny of these .

**Comment by lwfinger** [comment]
HP screwed up both the RTL8723BE and RTL8723DE by using only one antenna in the laptop, which is OK. Their failure is that they programmed the ROM to indicate that the antenna was actually attached to the other connector. Next they patched the Windows driver to ignore the ROM value. The original Linux driver is coded to use the value in the ROM, which ends up with NO antenna connected.

Do the following:
sudo nano /etc/modprobe.d/50-rtl8723de.conf

Once nano starts, then enter one line that says "options rtl8723de ant_sel=2" without the "", of course. Save the file and do a cold reboot. To make certain that the new parameter is applied, the power MUST be off on the chip.

I predict that the signal will be improved a lot.

Next do a Google search for "rtl8723be ant_sel" to learn what you just did.

**Comment by pandey246** [comment]
Thanks a lot.You are genius .Now everything is working fine.thanksssss....

**Comment by pandey246** [comment]
In the same device,audio is also very low.Do you know from where it can be increased?I mean i need to install some driver but don't know from where... Bluetooth is also not working.

**Comment by lwfinger** [comment]
Why are you bothering me about audio? Did I publish an audio driver? Non that I recall/

Congratulations - you have now gotten yourself blacklisted from my attention.
