### ISSUE TITLE
multiple warnings on make install

### ISSUE THREAD

**Issue by fvalenduc** [lwfinger/rtl8723be#14]
When installing the modules, I get plenty of warnings:

WARNING: module rtl_pci uses symbol rtl_swlps_beacon from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_deinit_deferred_work from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_check_beacon_key from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_efuse_ops_init from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_deinit_core from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol read_efuse_byte from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol show_it_mac from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_collect_scan_list from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_global_var from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_init_core from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_action_proc from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_lps_change_work_callback from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_init_rx_config from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_tid_to_ac from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_ops from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_deinit_rfkill from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_p2p_info from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_lps_leave from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_recognize_peer from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_is_special_data from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_init_rfkill from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_tx_mgmt_proc from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.
WARNING: module rtl_pci uses symbol rtl_beacon_statistic from namespace /usr/src/rtlwifi_new/rtlwifi, but does not import it.

It's the case for all the modules. It also happens at the end of the compilation.

**Comment by lwfinger** [comment]
That is a kernel problem. Ignore it. They will go away eventually.
