### ISSUE TITLE
signed modules can not be loaded

### ISSUE THREAD

**Issue by fvalenduc** [lwfinger/rtl8723be#15]
I try to use signing key for the modules but it doesn't seems to work. After I have installed the modules, I run this command
/usr/src/linux-5.3/scripts/sign-file sha512 /usr/src/linux-5.3/certs/signing_key.pem /usr/src/linux-5.3/certs/signing_key.x509 rtl8723de.ko
But when I load the modules, it doesn't work because the required signing key is not available.
However, it work for other out-of-tree modules (virtualbox drivers) with the same key.

Do you know why the same doesn't work with rtlwifi drivers ?

**Comment by lwfinger** [comment]
No.

**Comment by fvalenduc** [comment]
So what I am doing wrong ? I run the same command on vbox drivers and on rtlwifi drivers. It works for vbox drivers and it doesn't for rtlwifi. I can not explain that.

**Comment by lwfinger** [comment]
Nor can I. You have more experience with signing than I do.

**Comment by fvalenduc** [comment]
In fact I had no signed the other modules needed by rtl8723de, so these could'nt be loaded. It obviously works if I sign all modules.
