### ISSUE TITLE
Readme points to non-existing lwfinger/rtlwifi_new

### ISSUE THREAD

**Issue by laur89** [lwfinger/rtl8723be#17]

**Comment by axelnfs** [comment]
hello, im a new user for ubuntu, i cant find the rtl8723de drivers for my notebook, there are many forums on the internet citing the address with this specific driver, I do not know if someone would have this, I would really appreciate it, thank you all

**Comment by lwfinger** [comment]
To get the RTL8723DE driver, run the following commands as your normal user:
git clone https://github.com/lwfinger/rtw88.git
cd rtw88
make
sudo make install

The README.md  describes the packages you will need.
