### ISSUE TITLE
has rtlwifi_new repo been deleted ?

### ISSUE THREAD

**Issue by navilg** [lwfinger/rtl8723be#18]
I do not find rtlwifi_new repo. is rtlwifi_new repository deleted ? Could you please let me know if we have any other alternative for rtl8723be.
https://github.com/lwfinger/rtlwifi_new

@lwfinger , Could you please confirm ?

**Comment by lwfinger** [comment]
Yes it has. The alternatives are the kernel, the Backports project, or this repo;.
