### ISSUE TITLE
https://github.com/lwfinger/rtlwifi_new.git gives not found 404

### ISSUE THREAD

**Issue by omazouz** [lwfinger/rtl8723be#19]
Hello I am in real need of your drivers but I can not seem to be able to acces the link provided: https://github.com/lwfinger/rtlwifi_new.git

it gives 404, I would assume its private or its been deleted. Can you please let me know how to access it or if its deleted so that I go look for other solutions?

Many thanks :pray:

**Comment by lwfinger** [comment]
It has been deleted. For most drivers, the old repo just duplicated the kernel, which should be used. If you have an RTL8723DE, or an RTL8821CE, then use the repo at https://github.com/lwfinger/rtw88.com.

If you really want to use the old drivers, my repo was cloned a number of times. Of course, I no longer support any of those.

**Comment by AbhishekThapaKshetri** [comment]
Not get another link

**Comment by lwfinger** [comment]
That repo was closed. Either use the drivers in the kernel, or from the backports project: https://backports.wiki.kernel.org/index.php/Releases

**Comment by AbhishekThapaKshetri** [comment]
I just updated to new version its work usingusb thretaning
