### ISSUE TITLE
This repo is obsolete and the repo "rtlwifi_new" is deleted

### ISSUE THREAD

**Issue by Rami-Majdoub** [lwfinger/rtl8723be#23]
where can i find the new configuration?

**Comment by lwfinger** [comment]
In the kernel. If your kernel is too old to have rtl8723be built-in, then use the backports project.

**Comment by Rami-Majdoub** [comment]
i have Ubuntu 20.04.1 LTS and the wifi signal is weak (compared to windows). I saw many articles mention this repo. Should I reinstall the configuration, or it's older than the current one i have?

**Comment by lwfinger** [comment]
Have you investigated the ant_sel parameter?

**Comment by Rami-Majdoub** [comment]
I did and it's still weak.
I run:
sudo modprobe -rv rtl8723be
sudo modprobe rtl8723be ant_sel=2
I tried  ant_sel=1, but it displayed an empty list.

**Comment by lwfinger** [comment]
Are yiu aware that I did not write that driver? I only helped get it into the kernel. I am not an employee of Realtek, nor do I have access to any internal documents.

What do you mean weak? What signal strength do you get, and what distance are you from the AP?
