### ISSUE TITLE
lwfinger/rtlwifi_new page not found

### ISSUE THREAD

**Issue by OluA** [lwfinger/rtl8723be#24]
Hi,

obsolete rtl8723be redirects to https://github.com/lwfinger/rtlwifi_new.

New repo returns '404 - page not found'.

Please can you share correct link/repo?

Regards

**Comment by lwfinger** [comment]
No. rtlwifi_new was deleted. If your kernel does not support your unnamed device, then google "backports Linux". The latest versions of the kernel drivers will be there.
